// Code generated by goctl. DO NOT EDIT.
// Source: mixinsnapshotsrv.proto

package server

import (
	"context"

	"github.com/lixvyang/betxin-micro/service/mixinsnapshot/rpc/internal/logic"
	"github.com/lixvyang/betxin-micro/service/mixinsnapshot/rpc/internal/svc"
	"github.com/lixvyang/betxin-micro/service/mixinsnapshot/rpc/pb/pb"
)

type MixinsnapshotsrvServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMixinsnapshotsrvServer
}

func NewMixinsnapshotsrvServer(svcCtx *svc.ServiceContext) *MixinsnapshotsrvServer {
	return &MixinsnapshotsrvServer{
		svcCtx: svcCtx,
	}
}

// -----------------------mixinsnapshot-----------------------
func (s *MixinsnapshotsrvServer) AddMixinsnapshot(ctx context.Context, in *pb.AddMixinsnapshotReq) (*pb.AddMixinsnapshotResp, error) {
	l := logic.NewAddMixinsnapshotLogic(ctx, s.svcCtx)
	return l.AddMixinsnapshot(in)
}

func (s *MixinsnapshotsrvServer) UpdateMixinsnapshot(ctx context.Context, in *pb.UpdateMixinsnapshotReq) (*pb.UpdateMixinsnapshotResp, error) {
	l := logic.NewUpdateMixinsnapshotLogic(ctx, s.svcCtx)
	return l.UpdateMixinsnapshot(in)
}

func (s *MixinsnapshotsrvServer) DelMixinsnapshot(ctx context.Context, in *pb.DelMixinsnapshotReq) (*pb.DelMixinsnapshotResp, error) {
	l := logic.NewDelMixinsnapshotLogic(ctx, s.svcCtx)
	return l.DelMixinsnapshot(in)
}

func (s *MixinsnapshotsrvServer) GetMixinsnapshotById(ctx context.Context, in *pb.GetMixinsnapshotByIdReq) (*pb.GetMixinsnapshotByIdResp, error) {
	l := logic.NewGetMixinsnapshotByIdLogic(ctx, s.svcCtx)
	return l.GetMixinsnapshotById(in)
}

func (s *MixinsnapshotsrvServer) SearchMixinsnapshot(ctx context.Context, in *pb.SearchMixinsnapshotReq) (*pb.SearchMixinsnapshotResp, error) {
	l := logic.NewSearchMixinsnapshotLogic(ctx, s.svcCtx)
	return l.SearchMixinsnapshot(in)
}
