// Code generated by goctl. DO NOT EDIT.
package types

type Category struct {
	Id           int64  `json:"id"`
	CategoryName string `json:"category_name"`
}

type CreateCategoryReq struct {
	CategoryName string `json:"category_name"`
}

type CreateCategoryResp struct {
	Errmsg
	Data *string `json:"data"`
}

type ListCategoryResp struct {
	Errmsg
	Data []Category `json:"data"`
}

type GetCategoryReq struct {
	Id int64 `path:"id"`
}

type GetCategoryResp struct {
	Errmsg
	Data Category `json:"data"`
}

type Errmsg struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
