// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	topic "github.com/lixvyang/betxin-micro/service/topic/api/internal/handler/topic"
	"github.com/lixvyang/betxin-micro/service/topic/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/topic",
				Handler: topic.CreateTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/topic",
				Handler: topic.DeleteTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topic",
				Handler: topic.ListTopicHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
