// Code generated by goctl. DO NOT EDIT.
// Source: mixinsnapshotsrv.proto

package mixinsnapshotsrv

import (
	"context"

	"github.com/lixvyang/betxin-micro/service/mixinsnapshot/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMixinsnapshotReq      = pb.AddMixinsnapshotReq
	AddMixinsnapshotResp     = pb.AddMixinsnapshotResp
	DelMixinsnapshotReq      = pb.DelMixinsnapshotReq
	DelMixinsnapshotResp     = pb.DelMixinsnapshotResp
	GetMixinsnapshotByIdReq  = pb.GetMixinsnapshotByIdReq
	GetMixinsnapshotByIdResp = pb.GetMixinsnapshotByIdResp
	Mixinsnapshot            = pb.Mixinsnapshot
	SearchMixinsnapshotReq   = pb.SearchMixinsnapshotReq
	SearchMixinsnapshotResp  = pb.SearchMixinsnapshotResp
	UpdateMixinsnapshotReq   = pb.UpdateMixinsnapshotReq
	UpdateMixinsnapshotResp  = pb.UpdateMixinsnapshotResp

	Mixinsnapshotsrv interface {
		// -----------------------mixinsnapshot-----------------------
		AddMixinsnapshot(ctx context.Context, in *AddMixinsnapshotReq, opts ...grpc.CallOption) (*AddMixinsnapshotResp, error)
		UpdateMixinsnapshot(ctx context.Context, in *UpdateMixinsnapshotReq, opts ...grpc.CallOption) (*UpdateMixinsnapshotResp, error)
		DelMixinsnapshot(ctx context.Context, in *DelMixinsnapshotReq, opts ...grpc.CallOption) (*DelMixinsnapshotResp, error)
		GetMixinsnapshotById(ctx context.Context, in *GetMixinsnapshotByIdReq, opts ...grpc.CallOption) (*GetMixinsnapshotByIdResp, error)
		SearchMixinsnapshot(ctx context.Context, in *SearchMixinsnapshotReq, opts ...grpc.CallOption) (*SearchMixinsnapshotResp, error)
	}

	defaultMixinsnapshotsrv struct {
		cli zrpc.Client
	}
)

func NewMixinsnapshotsrv(cli zrpc.Client) Mixinsnapshotsrv {
	return &defaultMixinsnapshotsrv{
		cli: cli,
	}
}

// -----------------------mixinsnapshot-----------------------
func (m *defaultMixinsnapshotsrv) AddMixinsnapshot(ctx context.Context, in *AddMixinsnapshotReq, opts ...grpc.CallOption) (*AddMixinsnapshotResp, error) {
	client := pb.NewMixinsnapshotsrvClient(m.cli.Conn())
	return client.AddMixinsnapshot(ctx, in, opts...)
}

func (m *defaultMixinsnapshotsrv) UpdateMixinsnapshot(ctx context.Context, in *UpdateMixinsnapshotReq, opts ...grpc.CallOption) (*UpdateMixinsnapshotResp, error) {
	client := pb.NewMixinsnapshotsrvClient(m.cli.Conn())
	return client.UpdateMixinsnapshot(ctx, in, opts...)
}

func (m *defaultMixinsnapshotsrv) DelMixinsnapshot(ctx context.Context, in *DelMixinsnapshotReq, opts ...grpc.CallOption) (*DelMixinsnapshotResp, error) {
	client := pb.NewMixinsnapshotsrvClient(m.cli.Conn())
	return client.DelMixinsnapshot(ctx, in, opts...)
}

func (m *defaultMixinsnapshotsrv) GetMixinsnapshotById(ctx context.Context, in *GetMixinsnapshotByIdReq, opts ...grpc.CallOption) (*GetMixinsnapshotByIdResp, error) {
	client := pb.NewMixinsnapshotsrvClient(m.cli.Conn())
	return client.GetMixinsnapshotById(ctx, in, opts...)
}

func (m *defaultMixinsnapshotsrv) SearchMixinsnapshot(ctx context.Context, in *SearchMixinsnapshotReq, opts ...grpc.CallOption) (*SearchMixinsnapshotResp, error) {
	client := pb.NewMixinsnapshotsrvClient(m.cli.Conn())
	return client.SearchMixinsnapshot(ctx, in, opts...)
}
